
title = "Kevin Liao"
author = "Kevin"
#copyright = "2020-2021"
description = "For Love"
profilePicture = "images/profile.jpg"
keywords = ""
favicon = "favicons/"
# example ["css/custom.css"]
customCss = []
# example ["js/custom.js"]
customJs = [] 
mainSections = ["post"]
images = ["images/site-feature-image.png"]
doNotLoadAnimations = false
# Form Spree Contact Form
#contactFormAction = "https://formspree.io/f/your-form-hash-here"
# Google Site Verify
#googleSiteVerify = "ABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789"
singleDateFormat = "2006/1/2"
indexDateFormat = "2006/1/2"
listDateFormat = "2006/1/2"
# Commento Comments
# CommentoURL = "https://commento.example.com/js/commento.js"
# Read More links for truncated summaries
# readMore = true
# postSectionName = "blog"


[simpleAnalytics]
# enable = true
# customurl = "https://analytics.example.com"

## Math settings
[math]
enable = false  # options: true, false. Enable math support globally, default: false. You can always enable math on per page.
use = "katex"  # options: "katex", "mathjax". default is "katex".


## Social links
# use 'fab' when brand icons, use 'fas' when standard solid icons.
# [[socialIcons]]
# icon = "fab fa-linkedin"
# title = "Linkedin"
# url = "https://de.linkedin.com/"

# [[socialIcons]]
# icon = "fab fa-instagram"
# title = "instagram"
# url = "https://www.instagram.com/"

[[socialIcons]]
icon = "fab fa-weixin"
title = "Wechat"
url = "https://u.wechat.com/MJDtzlyO9eNzFTXaSqK5pac"

[[socialIcons]]
icon = "fab fa-github"
title = "GitHub"
url = "https://github.com/imkevinliao/blog"


[[socialIcons]]
icon = "fas fa-envelope"
title = "e-mail"
url = "mailto:im.kevinliao@gmail.com"